### ISSUE TITLE
chrono perspective is empty

### ISSUE THREAD

**Issue by runrin** [xgi/castero#172] opened 2021-05-29 22:41 UTC
I just built e93e9af and my 5th perspective doesn't show any episodes for some reason.

**Comment by xgi** [comment] 2021-05-30 14:25
I'm not able to reproduce this on any of my setups, so I'm not sure what the issue is. It sounds dumb, but have you tried leaving the 5th perspective open for some time to see if the list loads later?

**Comment by runrin** [comment] 2021-05-30 21:14
Okay, so I did some testing and I have the following to report:

*  I left my regular set of feeds sitting on the chrono perspective for over an hour and it did not load
*  I was able to get it to work with as many as 3802 episodes
*  I was able to get it to fail with as few as 1742 episodes  

To reproduce try adding the following two feeds to an empty setup:
`https://blogs.fangraphs.com/feed/effectively-wild`
`https://feeds.megaphone.fm/TAMC2240814899`

* I was able to get it to work with each of these in a feed by itself
* Effectively Wild was part of my test with 3802 episodes, and it worked fine there, but those two together causes it to fail

Let me know if I can help with more information.

**Comment by xgi** [comment] 2021-05-30 21:45
I was able to reproduce the issue by adding those feeds you listed. I haven't looked into the cause yet, but thanks for the testing!

(I also would have been very afraid if it actually loaded after an hour, haha. I was thinking like 30 seconds at most.)

**Comment by xgi** [comment] 2021-05-31 00:55
Fixed with #173. Turns out some feeds don't include a timezone in their release dates, which broke the sorter. They [should be required](https://validator.w3.org/feed/docs/error/InvalidRFC2822Date.html), but I've added a failsafe. Thanks!

**Closed by xgi** 2021-05-31 00:55 UTC
