### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by aplatypus** [xgi/castero#4] opened 2018-11-22 07:05 UTC
This project page:
- https://pypi.org/project/castero/

Looked as if we can use Python 3.  alas, it doesn't run.

Is there a process to do that?

**Comment by xgi** [comment] 2018-11-22 18:06
The client actually exclusively supports Python 3, so it should work! Can you let me know any error messages you are getting, as well as your exact Python version? (`python -V`)

**Comment by aplatypus** [comment] 2018-11-22 23:09
After installing as logged below.  May be everything worked ok.  This is Ubuntu 18.10

```
 $ castero
castero: command not found
 $ whereis castero
castero:
 $ ll  ~/.config/castro
ls: cannot access '/home/william/.config/castro': No such file or directory
 $ md ~/.config/castro
 $ 
 $ castero
castero: command not found
 $ 
```


```
$ python --version
Python 2.7.15+

$ python3 --version
Python 3.6.7
```


Installing on python3

```
$ pip3 install castero
Collecting castero
  Using cached https://files.pythonhosted.org/packages/56/a3/b36965bd110205e2f4b4f313da108822a1b81d6b02d07d6026a23624d9aa/castero-0.3.1-py3-none-any.whl
Collecting python-vlc (from castero)
Collecting requests (from castero)
  Using cached https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests->castero)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests->castero)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->castero)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->castero)
  Using cached https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl
Installing collected packages: python-vlc, idna, urllib3, chardet, certifi, requests, castero
Successfully installed castero-0.3.1 certifi-2018.10.15 chardet-3.0.4 idna-2.7 python-vlc-3.0.4106 requests-2.20.1 urllib3-1.24.1

$  pip3 install castero --upgrade
Collecting castero
  Using cached https://files.pythonhosted.org/packages/56/a3/b36965bd110205e2f4b4f313da108822a1b81d6b02d07d6026a23624d9aa/castero-0.3.1-py3-none-any.whl
Collecting python-vlc (from castero)
Collecting requests (from castero)
  Using cached https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests->castero)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->castero)
  Using cached https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests->castero)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->castero)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Installing collected packages: python-vlc, urllib3, certifi, idna, chardet, requests, castero
Successfully installed castero-0.3.1 certifi-2018.10.15 chardet-3.0.4 idna-2.7 python-vlc-3.0.4106 requests-2.20.1 urllib3-1.24.1
```

Checking VLC ...
```
vlc --version
VLC media player 3.0.4 Vetinari (revision 3.0.4-0-gf615db6332)
VLC version 3.0.4 Vetinari (3.0.4-0-gf615db6332)
Compiled by buildd on lgw01-amd64-060.buildd (Sep 27 2018 17:31:24)
Compiler: gcc version 8.2.0 (Ubuntu 8.2.0-7ubuntu1)
This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute it under the terms of the GNU General Public License;
see the file named COPYING for details.
Written by the VideoLAN team; see the AUTHORS file.
```

**Comment by aplatypus** [comment] 2019-02-05 22:53
Hi short update.

The install process still didn't work on thie PC (using Python2 nor Python3) and via PIP.  Ubuntu 18.10 with `apt install pythong 3` -- Expected that would be sufficient.

I was able to build and install using the GitHub project.  So if you are having trouble do a clone/copy and have at it.

```
sudo python3 setup.py install
```

Instructions are on the Readme file.

**Comment by xgi** [comment] 2019-02-07 00:21
Closing since this seems resolved.

**Closed by xgi** 2019-02-07 00:21 UTC

**Comment by aplatypus** [comment] 2019-02-10 22:10
I am unclear about how an issue about Castro failing to install can be closed when it is not installing.

The woraround of building from source, is the opposite of having a working "Install" process.

**Comment by xgi** [comment] 2019-02-10 23:49
Sorry, perhaps I misunderstood your previous comment.

However, since installing from the source fixes your issue, I'm inclined to believe that the issue is not on my end. The only installation methods I support are from the source (`setup.py install`) or via Pip, which just does the same thing with a specific version. Perhaps your issue was fixed in a recent update that has not been uploaded to PyPI.

Additionally, you haven't really said what the problem actually is; just that it "doesn't work."
