### ISSUE TITLE
[Feature Request]: Add MPRIS Support For Linux Users

### ISSUE THREAD

**Issue by ethanmassie** [xgi/castero#203] opened 2023-03-27 15:21 UTC
Implementing the [MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/) API will provide multimedia control support to castero (i.e bluetooth headphone controls, keyboard controls, applets like kde media player etc.).  

It looks like this can be implemented with the [mpris-server](https://pypi.org/project/mpris-server/) python package.

**Comment by KiaraGrouwstra** [comment] 2024-04-28 22:38
this seems a duplicate of #110

**Closed as not planned** 2024-04-29 13:30 UTC
