### ISSUE TITLE
can castero be faster?

### ISSUE THREAD

**Issue by Monirzadeh** [xgi/castero#64] opened 2019-11-12 09:47 UTC
i start use and review castero
i fell castero startup is slow ( i know that is python program)
i add only one feed only ( i am not test more feed can affect that)
that is output of time for ranger and castero
```
➜  ~ time ranger
ranger  0.47s user 0.02s system 47% cpu 1.027 total
➜  ~ time ranger
ranger  0.47s user 0.02s system 43% cpu 1.124 total
➜  ~ time ranger
ranger  0.45s user 0.04s system 45% cpu 1.059 total
➜  ~ time castero 
castero  0.80s user 0.46s system 64% cpu 1.946 total
➜  ~ time castero
castero  0.82s user 0.42s system 59% cpu 2.082 total
➜  ~ time castero
castero  0.81s user 0.44s system 38% cpu 3.215 total

```
if reading from disk make castero slower ranger has more config file.
startup and cpu usage is so high.
i think ranger is slow to but feature couldn't found any where (image preview)
which part of code could make castero slow?
have a podcast player in terminal is so awesome and thanks for your program so much.

**Comment by rien333** [comment] 2019-11-12 17:43
cpu usage on start is normal here (about 50% of one cpu).   The ranger and castero comparison is fairly unhelpful, they're completely different programs. You could make the comparison fairer if you compare another python (podcast) program.  That said, if it takes less than one second to load, you're really not loosing any time (you've probably lost more time writing this issue than you would ever lose from opening castero). 

> which part of code could make castero slow?

You might be able to do some (micro-)optimizations by changing stuff in your castero config. The following setting is espcially crucial for fast startup times:

```conf
[feeds]
# Whether to reload/refresh your feeds when the client starts. Depending on how
# many feeds you have, this operation may take a long time.
# default: False
reload_on_start = False
```

Or use a profiler maybe.

**Comment by rien333** [comment] 2019-11-12 18:13
I used pyinstrument to profile castero: https://gist.github.com/rien333/c610f9eb284c773b140ad7c24df16749

Nothing too interesting, but the  beautiful soup html parser that serves as an helper to castero seems to be a tiny bottleneck.  (but really, it's not that slow) I suppose you could try and start it asynchronously/later, but I'm not sure if anyone is interested in that.

**Comment by xgi** [comment] 2019-11-16 01:35
I agree that I don't think there is a notable performance issue. None of the metrics in this thread (thanks by the way) are particularly concerning to me. However, better performance is always obviously a good thing. I don't plan to take action on this issue now, but I'll leave it open since I'm sure at some point I'll go through and try to improve some of these latencies.

**Comment by hebecked** [comment] 2020-01-11 16:36
I just imported 1146 feeds (podcasts) totaling 20208 episodes.
The slow import was expected and is fine, though when opening the TUI it is super slow.
Scrolling from one menu point to another takes several seconds.
I guess it's because all episodes of a particular feed are loaded from the DB.
Is there a good way to only load the first x (e.g. 10) episodes and load the rest if the feed is actually selected?

**Comment by xgi** [comment] 2020-01-11 18:10
@hebecked Thanks for the feedback. I've noticed this latency before, but it was never bad enough for me to feel motivated fixing it (~30ms). It's definitely warranted now, though.

For posterity I'll go over my thought process. The issue is that when you go to the next feed, the UI doesn't update until the client has retrieved that feed's episodes. This is mostly a fixed-cost lookup (based on number of feeds), so I don't think there would be a significant performance improvement to only load a subset of them unless you had feeds with thousands of episodes.

The idea I have in mind is to have a separate thread to populate the episode menu so that the UI isn't impacted by this latency. So when you scroll over a feed the episode menu would appear blank for some time (ideally with a loading indicator) before it gets updated. This way you would be able to scroll through the feeds list quickly.

This is prone to all sorts of bugs though, so it might take me some time to implement. It could still be worth trying to reduce the load time as well, afterwords. Also, do you mind sharing your opml so that I can experiment with it?

**Comment by hebecked** [comment] 2020-01-11 20:15
@xgi Thanks so much for the quick response and your willingness to fix this.
Here the file I used. .opml ist not supported though, so I changed the file ending to .txt.
 
[PodcastAddict_export_20200111_145250.txt](https://github.com/xgi/castero/files/4049785/PodcastAddict_export_20200111_145250.txt)

**Comment by xgi** [comment] 2020-01-21 02:16
@hebecked I updated castero with #86 which reduces the latency in (mostly) the way I described above. The only difference is that the episode menu won't actually be blank temporarily, it will instead temporarily keep the contents of what was previously loaded. Regardless, the client should be much faster now.

I also noticed that the default footer message (which said like "Loaded x feeds with y episodes") was making some pretty heavy database requests, so I've simply removed it for now. I might add it back somewhere else (like the help menu) but I don't think it's a big deal.

I also also noticed while importing your list that the UX for importing wasn't very good for large OPMLs. So I created #87 which lists each feed as it's added, or any errors. There might be some more improvements to make (like optionally skipping feeds which already exist) but this is much better than the screen being blank for 20 minutes.

I'm going to close this issue now since I think there were some significant performance improvements. If anyone has additional performance concerns (especially specific ones), feel free to make another issue.

Thanks!

**Closed by xgi** 2020-01-21 02:16 UTC
