### ISSUE TITLE
Unnecessary repeated Downloads

### ISSUE THREAD

**Issue by mentrelli** [xgi/castero#113] opened 2020-06-02 09:49 UTC
After downloading an episode, if Castero is quitted and then launched again, the episode is not marked as downloaded, so when 's' is pressed it is downloaded another time. I noticed that for whatever reason a numeric string is prepended to the name of the downloaded file; this string changes every time Castero is launched, therefore each time the episode is downloaded, it is stored with a different filename.

**Comment by xgi** [comment] 2020-06-03 20:27
The number prefix is intentional, but it definitely shouldn't be changing (it should be unique per episode). I'll look into this, thanks.

**Comment by mentrelli** [comment] 2020-06-05 09:45
It this can be useful, I can add that if - in the same session - I download an episode (by pressing 's'), then I delete it (by pressing 's' again) and then I download it again a second time (by pressing 's' a third time), then the number prepended to the filename does not change (the name of the file downloaded the second time is the same as in the first download). But every time I close castero and then relaunch it, that number change so every time I launch castero no file is marked as downloaded. I am on castero 0.8.0. Thanks!

**Comment by sipior** [comment] 2020-06-29 17:05
I can confirm this behaviour (also on version 0.8.0), and have determined that it is reliably triggered by the reload/refresh feeds action. I don't see the problem upon client restart, likely because I have reload_on_start set to False. @mentrelli, could you verify that you have that variable set to True?

**Comment by mentrelli** [comment] 2020-06-29 19:20
Yes, I confirm that I had that variable set to True. After setting it to False, the problem does not occur at client restart. It definitely occurs when reloading/refreshing the feeds, though.

**Comment by xgi** [comment] 2020-07-16 07:21
Fixed with #131; sorry for the delay. Thanks for the reports!

**Closed by xgi** 2020-07-16 07:21 UTC
