### ISSUE TITLE
not showing ui

### ISSUE THREAD

**Issue by younlok** [xgi/castero#109] opened 2020-04-03 14:08 UTC
i was using castero for a long time 
but yesterday it broke 
when i run it i just see a blank terminal page 
i tried different terms but nothing

**Comment by tistatos** [comment] 2020-11-23 10:28
I have similar issue, running `castero`  will give no output.

**Comment by tistatos** [comment] 2020-11-23 11:54
After some digging with the source code it seems as if any call to `curses.curs_set` is causing my issue.

**Comment by xgi** [comment] 2020-11-23 19:11
I'm not able to reproduce this issue, so I didn't really have any leads to go on (hence I didn't reply earlier). However, crashing because of curs_set does make sense -- terminals that don't support custom visibility modes can cause an error.

I've made #150 which makes this functionality optional (i.e. it shouldn't crash the client if curs_set fails). I'll close this issue since this should be fixed, but since I can't actually test it myself, feel free to re-open if necessary. Thanks @tistatos for the details.

Thanks!

**Closed by xgi** 2020-11-23 19:11 UTC

**Comment by tistatos** [comment] 2020-11-24 09:34
I can confirm your fixes works for me! :+1: 
hopefully this resolves the issue for @younlok as well.
