### ISSUE TITLE
Reorder podcast

### ISSUE THREAD

**Issue by CaptaiNapalm** [xgi/castero#105] opened 2020-03-19 09:19 UTC
Hello,

Thanks a ton for castero, I use it everyday and it's a boon :]

I have a question, after a feed refresh, feeds in my main view are reordered once every few times and I can't figure out why. Pressing **I** allow me to invert the order, but I don't know the sorting order in the first place.
Also, would it be possible to freeze feeds sorting and to allow the user to order the feeds list ?

Thanks again for all the work, it's appreciated :+1:

**Comment by xgi** [comment] 2020-03-19 17:19
Feeds should just be sorted alphabetically -- assuming they are Latin letters, at least. And are you saying that when you refresh your feeds, they move around in the list? That's a funky bug if so.

One thing to keep in mind, which might be what the problem is, is that inverting the list is not maintained between client restarts. So pressing invert will make them sort Z-A but if you close and reopen the client it will be from A-Z again.

For manually ordering the list, I don't think I can do that, unfortunately. The main reason is honestly just that I don't think it's something many people would feel a need for and it's a lot of work. Besides just adding the controls and UX for moving things around, there are some underlying limitations with how menus currently work which make dynamic ordering more difficult.

**Comment by CaptaiNapalm** [comment] 2020-03-19 18:42
![image](https://user-images.githubusercontent.com/678705/77102184-b82df380-6a18-11ea-8227-4cf62aab88fc.png)

Unfortunately my feeds are not ordered alphabetically, and I can confirm that the list order changes every week or so, after a refresh if my memory serves me right. Pressing "I" reverse the list but it's still not in alphabetical order. I will look in sqlite db to find if there are some non-latin characters in feeds name.

I understand for manual re-ordering, thank you for considering it :)

**Comment by xgi** [comment] 2020-03-19 19:17
Strange, that's definitely a bug! I looked around a bit and I think that when the client retrieves the list of feeds from the sqlite database it doesn't explicitly set an ordering method, so sqlite just can theoretically just get them in an arbitrary order. For me (and everyone I've seen) this has always defaulted to alphabetical on the title, but I guess that's not guaranteed. It looks like your episode list is out of order too, which would be the same problem.

This should be a simple fix, so I'll plan on doing it today. Thanks!

**Comment by xgi** [comment] 2020-03-20 01:58
Fixed with #106. Feeds will be ordered alphabetically and will stay consistent. Let me know if you still have issues. Thanks!

**Closed by xgi** 2020-03-20 01:58 UTC
